//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xFaceLib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class xFaceLibResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal xFaceLibResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xFaceLib.Resources.xFaceLibResources", typeof(xFaceLibResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy app.xml error!.
        /// </summary>
        internal static string Copy_AppConfig_Error {
            get {
                return ResourceManager.GetString("Copy_AppConfig_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine is older than what app requires, may cause issues, please update!.
        /// </summary>
        internal static string Engine_Version_TooLow_Error {
            get {
                return ResourceManager.GetString("Engine_Version_TooLow_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no startApp in config.xml!.
        /// </summary>
        internal static string No_StartApp_In_Config {
            get {
                return ResourceManager.GetString("No_StartApp_In_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get app config from app.xml, please set app id and content properly!.
        /// </summary>
        internal static string Read_App_Config_Error {
            get {
                return ResourceManager.GetString("Read_App_Config_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start default app, please verify the default app is installed!.
        /// </summary>
        internal static string Start_DefaultApp_Error {
            get {
                return ResourceManager.GetString("Start_DefaultApp_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize System Failure!.
        /// </summary>
        internal static string System_Initialize_Error {
            get {
                return ResourceManager.GetString("System_Initialize_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update the default app with a different app id!.
        /// </summary>
        internal static string Update_DefaultApp_Id_NoMatch_Error {
            get {
                return ResourceManager.GetString("Update_DefaultApp_Id_NoMatch_Error", resourceCulture);
            }
        }
    }
}
